"use client"

import React from 'react';
import { motion } from 'framer-motion';
import { 
  TrendingDown, 
  Users, 
  AlertCircle,
  XCircle
} from 'lucide-react';

const fadeInUp = {
  hidden: { opacity: 0, y: 30 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.8, ease: [0.16, 1, 0.3, 1] as const } }
};

const staggerContainerLocal = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: { staggerChildren: 0.15 }
  }
};

export const HospitalWithoutPharmacyReality = () => {
  return (
    <section className="section-py bg-section-surface border-b border-muted">
      <div className="container-page">
        <motion.div 
          initial="hidden" 
          whileInView="visible" 
          viewport={{ once: true }} 
          variants={fadeInUp} 
          className="max-w-3xl mb-20 space-y-5"
        >
          <div className="eyebrow-wrap justify-start">
            <span className="eyebrow-line-l" />
            <span className="eyebrow-text">The healthcare reality</span>
          </div>
          <h2 className="text-h2 font-bold tracking-tight text-slate-900 leading-[1.1]">
            Clinical excellence. <br/>
            <span className="display-headline">
              Operational leakage.
            </span>
          </h2>
          <p className="text-body-lg text-body font-medium leading-relaxed max-w-2xl">
            Without an integrated fulfillment layer, your hospital isn't just losing revenue — you're losing the patient's trust and their post-visit journey.
          </p>
        </motion.div>

        <motion.div 
          initial="hidden" 
          whileInView="visible" 
          viewport={{ once: true }} 
          variants={staggerContainerLocal} 
          className="grid md:grid-cols-2 lg:grid-cols-4 gap-0 border border-slate-100 rounded-3xl overflow-hidden shadow-card"
        >
          {[
            {
              icon: TrendingDown,
              title: "Zero revenue capture",
              desc: "100% of the medicine value generated by your doctors is captured by outside retail pharmacies.",
              badge: "Revenue risk"
            },
            {
              icon: Users,
              title: "Patient drop-off",
              desc: "Patients who go elsewhere for medicines are 40% less likely to return for follow-up consults.",
              badge: "Retention risk"
            },
            {
              icon: AlertCircle,
              title: "Treatment non-compliance",
              desc: "Friction in finding medicines often leads to patients delaying or skipping their critical first dose.",
              badge: "Compliance risk"
            },
            {
              icon: XCircle,
              title: "Experience gap",
              desc: "The trust you built in the consulting room often ends abruptly at the hospital exit gate.",
              badge: "Experience risk"
            }
          ].map((item, i) => (
            <motion.div 
              key={i} 
              variants={fadeInUp} 
              className="p-8 md:p-10 bg-section-surface hover:bg-section-alt transition-all duration-500 flex flex-col group relative border-r last:border-r-0 border-slate-100"
            >
              <div className="absolute top-6 right-6 opacity-0 group-hover:opacity-100 transition-all duration-300 translate-y-2 group-hover:translate-y-0">
                <span className="badge badge-danger">
                  {item.badge}
                </span>
              </div>

              <div className="w-14 h-14 rounded-2xl bg-indigo-50 text-indigo-600 flex items-center justify-center mb-8 group-hover:scale-110 group-hover:bg-indigo-100 transition-all duration-500 shadow-card border border-indigo-100">
                <item.icon className="w-6 h-6 stroke-[1.5]" />
              </div>
              <h3 className="text-h3 font-bold mb-4 tracking-tight leading-tight">{item.title}</h3>
              <p className="text-sm font-medium text-subtitle leading-relaxed mb-6">{item.desc}</p>
              
              <div className="mt-auto pt-4 overflow-hidden">
                <div className="h-0.5 w-12 bg-slate-100 group-hover:w-full group-hover:bg-indigo-500 transition-all duration-700" />
              </div>
            </motion.div>
          ))}
        </motion.div>
      </div>
    </section>
  );
};